use shfmt for style formatting

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -4,239 +4,228 @@ BUILD_DIR="$(mktemp -d)"
 DOTFILE_DIR="$(pwd)"
 
 usage() {
-  echo "Usage: $0 [server|desktop]"
-  exit 2
+	echo "Usage: $0 [server|desktop]"
+	exit 2
 }
 
 except() {
-  # $1 -> reason
-  echo "Error: $1"
-  usage
+	# $1 -> reason
+	echo "Error: $1"
+	usage
 }
 
 _is_os() {
-  [ "$(uname)" = "$1" ]
+	[ "$(uname)" = "$1" ]
 }
 is_mac() {
-  _is_os "Darwin"
+	_is_os "Darwin"
 }
 is_linux() {
-  _is_os "Linux"
+	_is_os "Linux"
 }
 is_freebsd() {
-  _is_os "FreeBSD"
+	_is_os "FreeBSD"
 }
 is_openbsd() {
-  _is_os "OpenBSD"
+	_is_os "OpenBSD"
 }
 is_bsd() {
-  is_freebsd || is_openbsd
+	is_freebsd || is_openbsd
 }
 is_not_mac() {
-  ! is_mac
+	! is_mac
 }
 is_not_linux() {
-  ! is_linux
+	! is_linux
 }
 is_debian_linux() {
-  is_linux && [ -f /etc/debian_version ]
+	is_linux && [ -f /etc/debian_version ]
 }
 is_arch_linux() {
-  is_linux && [ -f /etc/arch-release ]
+	is_linux && [ -f /etc/arch-release ]
 }
 
 msg() {
-  printf "\r\033[2K\033[0;32m[ .. ] %s\033[0m\n" "$*"
+	printf "\r\033[2K\033[0;32m[ .. ] %s\033[0m\n" "$*"
 }
 
 git_has_pullable_tag() {
-  TARGET="$1"
-  RETVAL=1
+	TARGET="$1"
+	RETVAL=1
 
-  if [ ! -d "$TARGET" ]
-  then
-    RETVAL=0
-  else
-    cd "$TARGET" || exit
+	if [ ! -d "$TARGET" ]; then
+		RETVAL=0
+	else
+		cd "$TARGET" || exit
 
-    git fetch origin 1> /dev/null
-    LATEST_TAG="$(git describe --abbrev=0 --tags --match 'v[0-9]*' origin)"
+		git fetch origin 1>/dev/null
+		LATEST_TAG="$(git describe --abbrev=0 --tags --match 'v[0-9]*' origin)"
 
-    if [ "$(git rev-parse @)" != "$(git rev-parse @\{"$LATEST_TAG"\} 2> /dev/null)" ]
-    then
-      RETVAL=0
-    fi
-    cd - 1> /dev/null || exit
-  fi
+		if [ "$(git rev-parse @)" != "$(git rev-parse @\{"$LATEST_TAG"\} 2>/dev/null)" ]; then
+			RETVAL=0
+		fi
+		cd - 1>/dev/null || exit
+	fi
 
-  return "$RETVAL"
+	return "$RETVAL"
 }
 
 git_has_pullable_master() {
-  TARGET="$1"
-  RETVAL=1
+	TARGET="$1"
+	RETVAL=1
 
-  if [ ! -d "$TARGET" ]
-  then
-    RETVAL=0
-  else
-    cd "$TARGET" || exit
+	if [ ! -d "$TARGET" ]; then
+		RETVAL=0
+	else
+		cd "$TARGET" || exit
 
-    git fetch origin 1> /dev/null
+		git fetch origin 1>/dev/null
 
-    if [ "$(git rev-parse @)" != "$(git rev-parse @\{u\} 2> /dev/null)" ]
-    then
-      RETVAL=0
-    fi
+		if [ "$(git rev-parse @)" != "$(git rev-parse @\{u\} 2>/dev/null)" ]; then
+			RETVAL=0
+		fi
 
-    cd - 1> /dev/null || exit
-  fi
+		cd - 1>/dev/null || exit
+	fi
 
-  return "$RETVAL"
+	return "$RETVAL"
 }
 
 git_clone_or_pull_tag() {
-  GIT_URL="$1"
-  TARGET="$2"
+	GIT_URL="$1"
+	TARGET="$2"
 
-  if [ ! -d "$TARGET" ]
-  then
-    msg "Installing $GIT_URL."
-    git clone "$GIT_URL" "$TARGET" 2> /dev/null
-  fi
+	if [ ! -d "$TARGET" ]; then
+		msg "Installing $GIT_URL."
+		git clone "$GIT_URL" "$TARGET" 2>/dev/null
+	fi
 
-  cd "$TARGET" || exit
+	cd "$TARGET" || exit
 
-  git fetch --tags origin 1> /dev/null
-  LATEST_TAG="$(git describe --abbrev=0 --tags --match 'v[0-9]*' origin)"
+	git fetch --tags origin 1>/dev/null
+	LATEST_TAG="$(git describe --abbrev=0 --tags --match 'v[0-9]*' origin)"
 
-  if [ "$(git rev-parse @)" != "$(git rev-parse @\{$LATEST_TAG\} 2> /dev/null)" ]
-  then
-    msg "Upgrading $TARGET to $LATEST_TAG"
-    git checkout "$LATEST_TAG" 2> /dev/null
-  fi
+	if [ "$(git rev-parse @)" != "$(git rev-parse @\{$LATEST_TAG\} 2>/dev/null)" ]; then
+		msg "Upgrading $TARGET to $LATEST_TAG"
+		git checkout "$LATEST_TAG" 2>/dev/null
+	fi
 
-  cd - 1> /dev/null || exit
+	cd - 1>/dev/null || exit
 }
 
 git_clone_or_pull_master() {
-  GIT_URL="$1"
-  TARGET="$2"
+	GIT_URL="$1"
+	TARGET="$2"
 
-  if [ ! -d "$TARGET" ]
-  then
-    msg "Installing $GIT_URL."
-    git clone "$GIT_URL" "$TARGET" 2> /dev/null
-  else
-    cd "$TARGET" || exit
+	if [ ! -d "$TARGET" ]; then
+		msg "Installing $GIT_URL."
+		git clone "$GIT_URL" "$TARGET" 2>/dev/null
+	else
+		cd "$TARGET" || exit
 
-    git fetch origin 1> /dev/null
+		git fetch origin 1>/dev/null
 
-    if [ "$(git rev-parse @)" != "$(git rev-parse @\{u\} 2> /dev/null)" ]
-    then
-      msg "Upgrading $TARGET to latest master"
-      git checkout master 2> /dev/null
-    fi
+		if [ "$(git rev-parse @)" != "$(git rev-parse @\{u\} 2>/dev/null)" ]; then
+			msg "Upgrading $TARGET to latest master"
+			git checkout master 2>/dev/null
+		fi
 
-    cd - 1> /dev/null || exit
-  fi
+		cd - 1>/dev/null || exit
+	fi
 }
 
 get_var_or() {
-  [ -z "$1" ] && echo "$2" || echo "$1"
+	[ -z "$1" ] && echo "$2" || echo "$1"
 }
 
 ensure_build_dir() {
-  mkdir -p "$BUILD_DIR/$1"
+	mkdir -p "$BUILD_DIR/$1"
 }
 
 append_to_file() {
-  # $1 -> type
-  # $2 -> file
-  # $3 -> alternate output file name
-  source="$DOTFILE_DIR/$1/$2"
-  source_os="$source.$(uname)"
-  [ -z "$3" ] && target="$BUILD_DIR/.${2#.}" || target="$BUILD_DIR/.${3#.}"
+	# $1 -> type
+	# $2 -> file
+	# $3 -> alternate output file name
+	source="$DOTFILE_DIR/$1/$2"
+	source_os="$source.$(uname)"
+	[ -z "$3" ] && target="$BUILD_DIR/.${2#.}" || target="$BUILD_DIR/.${3#.}"
 
-  [ -f "$source" ] && cat "$source" >> "$target"
-  [ -f "$source_os" ] && cat "$source_os" >> "$target"
+	[ -f "$source" ] && cat "$source" >>"$target"
+	[ -f "$source_os" ] && cat "$source_os" >>"$target"
 }
 
 install_binary() {
-  # $1 -> type
-  # $2 -> file
-  source="$DOTFILE_DIR/$1/bin/$2"
-  source_os="$source.$(uname)"
-  target="$BUILD_DIR/.local/bin/${2#.}"
+	# $1 -> type
+	# $2 -> file
+	source="$DOTFILE_DIR/$1/bin/$2"
+	source_os="$source.$(uname)"
+	target="$BUILD_DIR/.local/bin/${2#.}"
 
-  [ -f "$source" ] && cp "$source" "$target"
-  [ -f "$source_os" ] && cp "$source_os" "$target"
+	[ -f "$source" ] && cp "$source" "$target"
+	[ -f "$source_os" ] && cp "$source_os" "$target"
 }
 
 install_binaries() {
-  # $1 -> module
-  [ -d "$1/bin" ] && for BIN in "$1"/bin/*; do
-    source="$DOTFILE_DIR/$BIN"
-    bin_name="$(basename "$BIN")"
-    target="$BUILD_DIR/.local/bin/${bin_name#.}"
-    cp "$source" "$target"
-    chmod +x "$target"
-  done
+	# $1 -> module
+	[ -d "$1/bin" ] && for BIN in "$1"/bin/*; do
+		source="$DOTFILE_DIR/$BIN"
+		bin_name="$(basename "$BIN")"
+		target="$BUILD_DIR/.local/bin/${bin_name#.}"
+		cp "$source" "$target"
+		chmod +x "$target"
+	done
 }
 
 install_directory() {
-  # $1 -> type
-  # $2 -> source
-  # $3 -> target
-  source="$DOTFILE_DIR/$1/$2"
-  target="$BUILD_DIR/$3"
+	# $1 -> type
+	# $2 -> source
+	# $3 -> target
+	source="$DOTFILE_DIR/$1/$2"
+	target="$BUILD_DIR/$3"
 
-  mkdir -p "$target"
+	mkdir -p "$target"
 
-  [ -d "$source" ] && cp -a "$source" "$target"
+	[ -d "$source" ] && cp -a "$source" "$target"
 }
 
 uncallable() {
-  ! command -v "$1" > /dev/null
+	! command -v "$1" >/dev/null
 }
 
 uncallable_mac() {
-  ! open -Ra "$1" 2> /dev/null
+	! open -Ra "$1" 2>/dev/null
 }
 
 install_pkg() {
-  # $1 -> pkg name
-  if is_mac;
-  then
-    brew install "$1"
-  fi
-  if is_freebsd;
-  then
-    sudo env ASSUME_ALWAYS_YES=yes pkg install "$1"
-  fi
-  if is_debian_linux;
-  then
-    sudo apt install -y "$1"
-  fi
+	# $1 -> pkg name
+	if is_mac; then
+		brew install "$1"
+	fi
+	if is_freebsd; then
+		sudo env ASSUME_ALWAYS_YES=yes pkg install "$1"
+	fi
+	if is_debian_linux; then
+		sudo apt install -y "$1"
+	fi
+	if is_arch_linux; then
+		sudo pacman -S --noconfirm "$1"
+	fi
 }
 
 ensure_pkg() {
-  # $1 -> cmd
-  # $2 -> optional package name
-  [ -z "$2" ] && pkg_name="$1" || pkg_name="$2"
+	# $1 -> cmd
+	# $2 -> optional package name
+	[ -z "$2" ] && pkg_name="$1" || pkg_name="$2"
 
-  if is_mac;
-  then
-    if uncallable_mac "$1" && uncallable "$1";
-    then
-      install_pkg "$pkg_name"
-    fi
-  else
-    if uncallable "$1";
-    then
-      install_pkg "$pkg_name"
-    fi
-  fi
+	if is_mac; then
+		if uncallable_mac "$1" && uncallable "$1"; then
+			install_pkg "$pkg_name"
+		fi
+	else
+		if uncallable "$1"; then
+			install_pkg "$pkg_name"
+		fi
+	fi
 }
 
 ###
@@ -245,9 +234,8 @@ ensure_pkg() {
 PROFILE="$1"
 PROFILEFILE="profiles/$PROFILE"
 
-if [ ! -f "$PROFILEFILE" ];
-then
-  except "Unknown profile"
+if [ ! -f "$PROFILEFILE" ]; then
+	except "Unknown profile"
 fi
 
 ###
@@ -256,15 +244,14 @@ fi
 msg "Building dotfiles in $BUILD_DIR."
 
 # Configure home. Export variables that need to be accessible later on.
-if is_mac
-then
-  CONFIG_DIR=$(get_var_or "$XDG_CONFIG_HOME" "$HOME/Library/Preferences/")
-  CACHE_DIR=$(get_var_or "$XDG_CACHE_HOME" "$HOME/Library/Caches/")
-  DATA_DIR=$(get_var_or "$XDG_DATA_HOME" "$HOME/Library/")
+if is_mac; then
+	CONFIG_DIR=$(get_var_or "$XDG_CONFIG_HOME" "$HOME/Library/Preferences/")
+	CACHE_DIR=$(get_var_or "$XDG_CACHE_HOME" "$HOME/Library/Caches/")
+	DATA_DIR=$(get_var_or "$XDG_DATA_HOME" "$HOME/Library/")
 else
-  CONFIG_DIR=$(get_var_or "$XDG_CONFIG_HOME" "$HOME/.config")
-  CACHE_DIR=$(get_var_or "$XDG_CACHE_HOME" "$HOME/.cache")
-  DATA_DIR=$(get_var_or "$XDG_DATA_HOME" "$HOME/.local/share")
+	CONFIG_DIR=$(get_var_or "$XDG_CONFIG_HOME" "$HOME/.config")
+	CACHE_DIR=$(get_var_or "$XDG_CACHE_HOME" "$HOME/.cache")
+	DATA_DIR=$(get_var_or "$XDG_DATA_HOME" "$HOME/.local/share")
 fi
 
 SYSTEMD_DIR="$CONFIG_DIR/systemd/user"
@@ -276,52 +263,44 @@ BUILD_SYSTEMD_DIR="${SYSTEMD_DIR#$HOME/}"
 BUILD_BIN_DIR="${BIN_DIR#$HOME/}"
 
 # Create build directory structure.
-for e in "$BUILD_CONFIG_DIR" "$BUILD_CACHE_DIR" "$BUILD_DATA_DIR" "$BUILD_BIN_DIR";
-do
-  ensure_build_dir "$e"
+for e in "$BUILD_CONFIG_DIR" "$BUILD_CACHE_DIR" "$BUILD_DATA_DIR" "$BUILD_BIN_DIR"; do
+	ensure_build_dir "$e"
 done
 is_linux && ensure_build_dir "$BUILD_SYSTEMD_DIR"
 
 # Directory layout
-if [ "$PROFILE" = "desktop" ] && is_not_mac
-then
-  for D in prj doc spool bkp tmp
-  do
-    ensure_build_dir "$D"
-  done
+if [ "$PROFILE" = "desktop" ] && is_not_mac; then
+	for D in prj doc spool bkp tmp; do
+		ensure_build_dir "$D"
+	done
 fi
 
-if [ "$PROFILE" = "desktop" ] && is_mac
-then
-  for D in Projects Backups Temp
-  do
-    ensure_build_dir "$D"
-  done
+if [ "$PROFILE" = "desktop" ] && is_mac; then
+	for D in Projects Backups Temp; do
+		ensure_build_dir "$D"
+	done
 fi
 
 # Install all modules for the chosen profile
-while read -r MODULE;
-do
-  msg "Preparing module $MODULE"
-  
-  # shellcheck source=modules/core/_init
-  . "modules/$MODULE/_init" 2> /dev/null
+while read -r MODULE; do
+	msg "Preparing module $MODULE"
 
-  for F in functions env aliases profile rc;
-  do
-    append_to_file "modules/$MODULE" "$F"
-  done
+	# shellcheck source=modules/core/_init
+	. "modules/$MODULE/_init" 2>/dev/null
 
-  install_binaries "modules/$MODULE"
+	for F in functions env aliases profile rc; do
+		append_to_file "modules/$MODULE" "$F"
+	done
 
-  for FUNC in "_deps" "_install"; do
-    if type "$FUNC" 2> /dev/null | grep -q function;
-    then
-      "$FUNC"
-      unset -f "$FUNC"
-    fi
-  done
-done < "$PROFILEFILE"
+	install_binaries "modules/$MODULE"
+
+	for FUNC in "_deps" "_install"; do
+		if type "$FUNC" 2>/dev/null | grep -q function; then
+			"$FUNC"
+			unset -f "$FUNC"
+		fi
+	done
+done <"$PROFILEFILE"
 
 # Modules:
 #
@@ -375,8 +354,8 @@ done < "$PROFILEFILE"
 #   done
 # fi
 
-[ -d "$DOTFILE_DIR/build.bkp" ] && rm -rf "$DOTFILE_DIR/build.bkp";
-[ -d "$DOTFILE_DIR/build" ] && mv "$DOTFILE_DIR/build" "$DOTFILE_DIR/build.bkp";
+[ -d "$DOTFILE_DIR/build.bkp" ] && rm -rf "$DOTFILE_DIR/build.bkp"
+[ -d "$DOTFILE_DIR/build" ] && mv "$DOTFILE_DIR/build" "$DOTFILE_DIR/build.bkp"
 mv "$BUILD_DIR" "$DOTFILE_DIR/build"
 
 msg "Built the following dotfiles dir:"
@@ -384,29 +363,29 @@ echo ""
 tree -a build
 
 while true; do
-  echo "Do you wish to install those dotfiles? Answer y or n."
-  read -r yn
-  case $yn in
-    [Yy]* )
-      find build/ | while read -r F; do
-        [ -d "$F" ] && mkdir -p "$HOME/${F#build/}"
-        [ -f "$F" ] && install -C -m 0644 "$F" "$HOME/${F#build/}"
-        # FIXME: cp -P doesn't work on *BSD, this will instead copy the file
-        #        and not the link.
-        [ -L "$F" ] && cp -P "$F" "$HOME/${F#build/}"
-      done
-      # FIXME: Fix up some permissions. Is there a better way to use the
-      #        install command?
-      [ -d "$HOME/.gnupg" ] && chmod 0700 "$HOME/.gnupg"
-      [ -f "$HOME/.xmonad/build" ] && chmod +x "$HOME/.xmonad/build"
-      # File globbing throws an error if the directory is empty. Test if
-      # $BIN_DIR has any files before expanding the directory.
-      [ -n "$(ls -A $BIN_DIR)" ] && for f in "$BIN_DIR"/*; do chmod +x "$f"; done
-      break
-      ;;
-    [Nn]* ) exit;;
-    * ) echo "Please answer yes or no.";;
-  esac
+	echo "Do you wish to install those dotfiles? Answer y or n."
+	read -r yn
+	case $yn in
+	[Yy]*)
+		find build/ | while read -r F; do
+			[ -d "$F" ] && mkdir -p "$HOME/${F#build/}"
+			[ -f "$F" ] && install -C -m 0644 "$F" "$HOME/${F#build/}"
+			# FIXME: cp -P doesn't work on *BSD, this will instead copy the file
+			#        and not the link.
+			[ -L "$F" ] && cp -P "$F" "$HOME/${F#build/}"
+		done
+		# FIXME: Fix up some permissions. Is there a better way to use the
+		#        install command?
+		[ -d "$HOME/.gnupg" ] && chmod 0700 "$HOME/.gnupg"
+		[ -f "$HOME/.xmonad/build" ] && chmod +x "$HOME/.xmonad/build"
+		# File globbing throws an error if the directory is empty. Test if
+		# $BIN_DIR has any files before expanding the directory.
+		[ -n "$(ls -A $BIN_DIR)" ] && for f in "$BIN_DIR"/*; do chmod +x "$f"; done
+		break
+		;;
+	[Nn]*) exit ;;
+	*) echo "Please answer yes or no." ;;
+	esac
 done
 
 # # Xmonad
